### ISSUE TITLE
Couldn't get post build model. Module: Android_Demo.app.main Variant: debug

### ISSUE THREAD

**Issue by hamiltonhzy** [BruceWind/AndroidRemoteBuildWithDocker#1]
Launching 'remote-build'
Couldn't get post build model. Module: Android_Demo.app.main Variant: debug

**Comment by BruceWind** [comment]
Hello, thanks for using this repo. We can talk in Chinese.


这是点击Android studio 界面上的build？

**Comment by hamiltonhzy** [comment]
是的

**Comment by BruceWind** [comment]
能否把你的配置截图？ 另外，我同时需要你项目的命令行编译的命令，有些项目可能做了特殊配置。

**Comment by hamiltonhzy** [comment]
![image](https://github.com/BruceWind/AndroidRemoteBuildWithDocker/assets/5715786/4f295994-8792-46f0-9a77-83a925ea53b4)

**Comment by hamiltonhzy** [comment]
mainframer.sh
./gradlew
:app:assembleDebug
-Pandroid.enableBuildCache=true

**Comment by hamiltonhzy** [comment]
就是按照你写的

**Comment by BruceWind** [comment]
这里有个stackoverflow 的QA，您可以先参考看看：https://stackoverflow.com/questions/70916786/com-android-tools-idea-run-apkprovisionexception-couldnt-get-post-build-model

**Comment by hamiltonhzy** [comment]
改成release吗

**Comment by BruceWind** [comment]
你可以先确保命令行里操作远程编译是能通过的，然后再用AS UI编译按钮。

另外，你的build.gradle 里是否有如下内容？
```
buildTypes {
    release {}
    debug{}

```

**Comment by BruceWind** [comment]
> 改成release吗

先 Invalidate caches 试试。

**Comment by hamiltonhzy** [comment]
Invalidate caches试过了，还是不行。

android {
  compileSdkVersion 33
  buildToolsVersion "30.0.2"

  defaultConfig {
    applicationId "com.android.hzy.demo"
    minSdkVersion 21
    targetSdkVersion 33
    versionCode 1
    versionName "1.0"

    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
  }

  buildTypes {
    debug {
    }
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
}

**Comment by BruceWind** [comment]
命令行可以跑吗？如果你的电脑是mac/linux ，你可以命令行里输入`mainframer.sh ./gradlew :app:assembleDebug -Pandroid.enableBuildCache=true`

BTW，我没在windows下尝试过。

**Comment by BruceWind** [comment]
这个看上去是个配置问题，我暂时手里没这个环境。晚上回去我会看下。

**Comment by hamiltonhzy** [comment]
编译是通过的，就是安装不行。

**Comment by hamiltonhzy** [comment]
mac

**Comment by BruceWind** [comment]
命令能跑通，说明远程编译是配置好了的。安装的过程是基于这个远程编译后的自动同步远端服务器上的编译出来的文件到本地，编译出的文件同步到本地后，apk也在里面，即可被AS识别自动走安装过程。
大体逻辑是这样，你可以先看看。 我不确定是因为AS更新了 某些逻辑发生了变化。

**Comment by hamiltonhzy** [comment]
![image](https://github.com/BruceWind/AndroidRemoteBuildWithDocker/assets/5715786/4b49d98f-bc5f-43d1-b82c-5c70af9e763d)
那可能是AS的问题吧，感谢大佬回复！

**Comment by BruceWind** [comment]
hi bro. 我在家里电脑测试了下。一切正常。
不过我的AS里配置的步骤跟readme里不太一样，我用了copy原来的旧的app配置，再点 `-` 删...... 后面步骤一样。
我测试安装 调试都可以的。
![Screenshot 2023-07-12 at 9 34 45 PM](https://github.com/BruceWind/AndroidRemoteBuildWithDocker/assets/6711309/061b758c-0b4d-4808-90de-6c1b832d7769)
![Screenshot 2023-07-12 at 9 37 16 PM](https://github.com/BruceWind/AndroidRemoteBuildWithDocker/assets/6711309/46314496-5a49-40de-824f-2d880f18e330)
![Screenshot 2023-07-12 at 9 35 04 PM](https://github.com/BruceWind/AndroidRemoteBuildWithDocker/assets/6711309/0b65a50e-05c6-486b-8c60-2b292c8507bf)

**Comment by BruceWind** [comment]
你看下远程编译后，从远端下载下来的文件里有没有编译好的apk。 AS应该可以自动识别到apk并安装才对。

**Comment by BruceWind** [comment]
再试了下按照readme里的步骤也是正常的。 看上去我这里AS版本也是最新的。

你可以尝试找个老Android项目测试下。我这里只有老的Android项目，我测试没问题。我现在不太熟悉现在新的项目的配置哪里有变化。

**Comment by BruceWind** [comment]
给你一个我搭建好的 远程的 docker环境试试,地址端口如下：  
`1.tcp.cpolar.cn:22426`，账号密码同readme里的描述。

**Comment by BruceWind** [comment]
If there is no more replies, I'm going to close this issue.
